### ISSUE TITLE
[Proposal] Function name and parenthesis should have no space in between

### ISSUE THREAD

**Issue by ldiqual** [siteline/eslint-config-siteline#5]
Our current style:

```
// Good
function test () { ... }

// Bad
function test() { ... }
```

I don't think I've ever seen this style enforced and I'd love to keep it consistent with some of the most [popular JS projects](https://www.npmjs.com/browse/depended):

No space:

 - [lodash](https://github.com/lodash/lodash/blob/master/isNull.js#L16)
 - [chalk](https://github.com/chalk/chalk/blob/master/source/index.js#L53)
 - [react / react-dom / prop-types](https://github.com/facebook/react/blob/master/packages/react/src/ReactElement.js#L25)
 - [commander](https://github.com/tj/commander.js/blob/master/index.js#L87)
 - [express](https://github.com/expressjs/express/blob/master/lib/express.js#L37)

Space:

 - [request](https://github.com/request/request/blob/master/index.js)
 - [moment](https://github.com/moment/moment/blob/develop/src/lib/moment/to.js#L5)

**Comment by arnmishra** [comment]
@ldiqual fyi looks like prettier enforces no space after function name

**Comment by ldiqual** [comment]
Prettier will take care of this – removing eslint's focus on code style
